// Minimal i18n constants. Decision #70 will layer a real i18n library
// on top later; this keeps user-visible strings centralised so the
// migration is a one-shot find-and-replace.
//
// Terminology stays generic on purpose: LANDR is a universal booking
// platform (paragliding, kayak, ski, yoga…). No vertical-specific
// labels here.

export const t = {
  app: {
    name: 'LANDR Operator Dashboard',
  },
  auth: {
    signInHeading: 'Sign in',
    signInDescription: 'Access your operator dashboard.',
    emailLabel: 'Email',
    emailPlaceholder: 'you@operator.example',
    passwordLabel: 'Password',
    passwordPlaceholder: '••••••••',
    submit: 'Sign in',
    submitting: 'Signing in…',
    signOut: 'Sign out',
    invalidEmail: 'Enter a valid email address.',
    passwordRequired: 'Password is required.',
    genericError: 'Unable to sign in. Check your credentials and try again.',
    loadingSession: 'Loading session…',
  },
  operator: {
    switcherLabel: 'Operator',
    noOperators: 'No operators available for this account.',
    switchTo: 'Switch operator',
    loading: 'Loading operators…',
  },
  nav: {
    sectionMain: 'Workspace',
    dashboard: 'Dashboard',
    bookings: 'Bookings',
    calendar: 'Calendar',
    contacts: 'Contacts',
    products: 'Products',
    reporting: 'Reporting',
    generalApprovals: 'Approvals',
    staff: 'Staff',
    settings: 'Settings',
    emailTemplates: 'Email templates',
    pickupLocations: 'Pickup locations',
  },
  theme: {
    switchToDark: 'Switch to dark theme',
    switchToLight: 'Switch to light theme',
  },
  userMenu: {
    label: 'User menu',
  },
  bookings: {
    title: 'Bookings',
    empty: 'No bookings yet.',
    loading: 'Loading bookings…',
    error: 'Failed to load bookings.',
    columnDate: 'Date',
    columnCustomer: 'Customer',
    columnProduct: 'Product',
    columnStatus: 'Status',
    columnPrice: 'Price',
    columnDays: 'Days',
    filterPlaceholder: 'Search bookings…',
    detailsTitle: 'Booking',
    detailsClose: 'Close',
    detail: {
      sectionStatus: 'Status',
      sectionCustomer: 'Customer',
      sectionDates: 'Dates',
      sectionPricing: 'Pricing',
      customerFirstName: 'First name',
      customerLastName: 'Last name',
      customerEmail: 'Email',
      customerPhone: 'Phone',
      dateRangeStart: 'Start date',
      dateRangeEnd: 'End date',
      selectedDaysLabel: 'Selected days',
      selectedDaysHint:
        'Click a day chip to toggle it on or off. Pricing recomputes on save.',
      noSelectedDays: 'No specific days selected for this line item.',
      grossTotalLabel: 'Gross total',
      recomputeHint: 'Recomputed automatically on save.',
      save: 'Save changes',
      saving: 'Saving…',
      cancel: 'Cancel',
      noChanges: 'No changes to save.',
      saveToastSuccess: 'Booking updated.',
      saveToastError: 'Failed to save booking.',
      stageTooltip: (code: string) => `Stage: ${code}`,
      itemHeading: (name: string | null, index: number) =>
        name ? name : `Line item ${index + 1}`,
    },
    cancel: {
      action: 'Cancel booking',
      dialogTitle: 'Cancel this booking?',
      dialogDescription:
        'The booking will be soft-cancelled. Capacity is released automatically. The audit trail is preserved.',
      reasonLabel: 'Reason (required)',
      reasonPlaceholder: 'Why are you cancelling?',
      reasonTooShort: 'Please give a reason of at least 3 characters.',
      cancelAction: 'Keep booking',
      confirmAction: 'Cancel booking',
      cancelling: 'Cancelling…',
      toastSuccess: 'Booking cancelled.',
      toastError: 'Failed to cancel booking.',
    },
    hotelUnblock: {
      label: 'Hotel confirmed — unblock booking',
      description:
        'This will move the booking to the next stage and notify the customer. Continue?',
      cancel: 'Keep waiting',
      confirm: 'Unblock booking',
      working: 'Unblocking…',
      toastSuccess: 'Booking unblocked.',
      toastError: 'Failed to unblock booking.',
    },
    stage: {
      pending: 'Pending',
      awaitingGeneralApproval: 'Awaiting approval',
      awaitingSecondaryApproval: 'Awaiting secondary approval',
      awaitingHotelApproval: 'Awaiting hotel',
      confirmed: 'Confirmed',
      finalised: 'Finalised',
      cancelled: 'Cancelled',
      noShow: 'No-show',
    },
  },
  calendar: {
    title: 'Calendar',
    loading: 'Loading calendar…',
    error: 'Failed to load calendar.',
    empty: 'No bookings scheduled.',
    viewMonth: 'Month',
    viewWeek: 'Week',
    viewDay: 'Day',
    rescheduleError: 'Could not reschedule booking.',
  },
  contacts: {
    title: 'Contacts',
    empty: 'No contacts yet.',
    loading: 'Loading contacts…',
    error: 'Failed to load contacts.',
    columnName: 'Name',
    columnEmail: 'Email',
    columnPhone: 'Phone',
    columnCreated: 'Created',
    columnStatus: 'Status',
    columnActivity: 'Activity',
    columnActions: 'Actions',
    filterPlaceholder: 'Search contacts…',
    statusActive: 'Active',
    statusErased: 'Erased',
    actionErase: 'GDPR erase',
    actionAudit: 'Audit log',
    actionEraseShort: 'Erase',
    erasing: 'Erasing…',
    eraseToastSuccess: 'Contact erased and audit log scrubbed.',
    eraseToastError: 'GDPR erase failed.',
    auditTitle: 'Audit log',
    auditEmpty: 'No audit entries.',
    auditLoading: 'Loading audit log…',
    auditError: 'Failed to load audit log.',
    auditClose: 'Close',
    eraseDialogTitle: 'Trigger GDPR erase',
    eraseDialogIntro:
      'This will scrub all PII from this contact, the audit log, and any linked bookings. Commercial fields are preserved per Spanish 6-year retention. This action is irreversible.',
    eraseDialogConfirmLabel: 'Type ERASE to confirm',
    eraseDialogReasonLabel: 'Jurisdiction note (required)',
    eraseDialogReasonPlaceholder: 'e.g. GDPR Art. 17 request via email 2026-05-…',
    eraseDialogCancel: 'Cancel',
    eraseDialogSubmit: 'Erase contact',
    activityRecent: 'Recent: ',
  },
  products: {
    title: 'Products & pricing',
    loading: 'Loading products…',
    error: 'Failed to load products.',
    empty: 'No products yet. Create one to get started.',
    noMatches: 'No products match your filter.',
    filterPlaceholder: 'Search products…',
    listAriaLabel: 'Products',
    createNew: 'New product',
    headingNew: 'New product',
    headingPick: 'Select a product',
    pickHint: 'Pick a product on the left to edit, or create a new one.',
    statusActive: 'Active',
    statusInactive: 'Inactive',

    fieldName: 'Name',
    fieldSlug: 'Slug',
    fieldSlugHint: 'Lowercase, used in URLs. Must be unique per operator.',
    fieldShortDescription: 'Short description',
    fieldDescription: 'Description',
    fieldDurationKind: 'Duration model',
    fieldDurationMinutes: 'Duration (minutes)',
    fieldFixedStartDate: 'Fixed start date',
    fieldFixedEndDate: 'Fixed end date',
    fieldFixedDatesHint: 'Leave both empty for a floating date range.',
    fieldPricingScheme: 'Default pricing scheme',
    fieldProductGroup: 'Product group',
    fieldSortOrder: 'Sort order',
    optionNone: '— None —',

    legendFlags: 'Flags',
    flagActive: 'Active',
    flagPubliclyListed: 'Publicly listed',
    flagNeedsProvider: 'Needs a provider',
    flagNeedsPickup: 'Needs pickup',
    flagRevenueThroughOperator: 'Revenue flows through operator',

    durationSingleDay: 'Single day',
    durationDateRange: 'Date range',
    durationTimeSlot: 'Time slot',

    save: 'Save changes',
    saving: 'Saving…',
    create: 'Create product',
    delete: 'Delete',
    deleting: 'Deleting…',
    confirmDelete:
      'Delete this product? This is a soft delete — it can be restored from the database if needed.',

    formCreateLabel: 'Create product form',
    formEditLabel: 'Edit product form',

    toastCreated: 'Product created.',
    toastUpdated: 'Product updated.',
    toastDeleted: 'Product deleted.',

    errorNameRequired: 'Name is required.',
    errorSlugRequired: 'Slug is required.',
    errorSlugFormat: 'Slug may only contain letters, numbers and hyphens.',
    errorDurationRequired: 'Time-slot products must specify a duration.',
    errorDateRangePaired: 'Set both the start and end date, or neither.',
  },
  generalApprovals: {
    title: 'Pending approvals',
    empty: 'No bookings awaiting general approval.',
    loading: 'Loading approval queue…',
    error: 'Failed to load approval queue.',
    columnDate: 'Date',
    columnCustomer: 'Customer',
    columnProduct: 'Product',
    columnPrice: 'Price',
    columnActions: 'Actions',
    actionApprove: 'Approve',
    actionReject: 'Reject',
    approveDialogTitle: 'Approve booking',
    approveDialogDescription:
      'The booking will move to confirmed. You can add an optional note.',
    rejectDialogTitle: 'Reject booking',
    rejectDialogDescription:
      'The booking will be declined. You can add an optional note for the record.',
    notePlaceholder: 'Optional note…',
    noteLabel: 'Note (optional)',
    cancel: 'Cancel',
    confirmApprove: 'Approve',
    confirmReject: 'Reject',
    approving: 'Approving…',
    rejecting: 'Rejecting…',
    toastApproved: 'Booking approved.',
    toastRejected: 'Booking rejected.',
    toastError: 'Action failed.',
  },
  staff: {
    title: 'Staff',
    subtitle:
      'Manage operator memberships, roles and per-user permissions.',
    loading: 'Loading staff…',
    error: 'Failed to load staff.',
    empty: 'No staff yet. Use “Invite by email” to add a member.',
    listAriaLabel: 'Staff memberships',
    filterPlaceholder: 'Search staff…',
    matches: (n: number, total: number) => `${n} / ${total}`,

    columnEmail: 'Email',
    columnRole: 'Role',
    columnPermissions: 'Permissions',
    columnJoined: 'Joined',
    columnActions: 'Actions',

    actionInvite: 'Invite by email',
    actionEdit: 'Edit',
    actionRevoke: 'Revoke',

    // Invite sheet
    inviteTitle: 'Invite by email',
    inviteDescription:
      'Add a user to this operator. The user must already exist in LANDR (signed-in once via the mobile app or dashboard).',
    inviteEmailLabel: 'Email',
    inviteEmailPlaceholder: 'staff@example.com',
    inviteRoleLabel: 'Role',
    invitePermissionsLabel: 'Permissions (JSON)',
    invitePermissionsHint:
      'Optional JSON object. Example: { "manage_bookings": true, "view_revenue": false }',
    inviteSubmit: 'Add membership',
    inviteSubmitting: 'Adding…',
    inviteCancel: 'Cancel',
    inviteToastSuccess: 'Staff member added.',
    inviteToastError: 'Failed to add staff member.',
    inviteUserNotFound:
      'No user found with that email. They must sign in to LANDR at least once first.',
    inviteEmailRequired: 'Enter a valid email address.',
    inviteRoleRequired: 'Role is required.',

    inviteDeferralNotice:
      'Email-invite send is deferred (landr-m05.15 Gmail OAuth). For now, the user must already be signed in to LANDR — this just links them to this operator.',

    // Edit sheet
    editTitle: 'Edit membership',
    editDescription:
      'Update the role and permissions for this staff member.',
    editRoleLabel: 'Role',
    editPermissionsLabel: 'Permissions (JSON)',
    editPermissionsHint:
      'Leave empty for no overrides. Must be a JSON object if set.',
    editSubmit: 'Save changes',
    editSubmitting: 'Saving…',
    editCancel: 'Cancel',
    editToastSuccess: 'Membership updated.',
    editToastError: 'Failed to update membership.',

    // Revoke confirm dialog
    revokeTitle: 'Revoke staff access?',
    revokeDescription:
      'This removes the membership for this user. They will no longer see this operator. Their global LANDR account is not affected. This action cannot be undone.',
    revokeConfirm: 'Type REVOKE to confirm',
    revokeCancel: 'Cancel',
    revokeSubmit: 'Revoke access',
    revokeSubmitting: 'Revoking…',
    revokeToastSuccess: 'Staff access revoked.',
    revokeToastError: 'Failed to revoke staff access.',

    permissionsParseError: 'Permissions JSON is invalid.',
  },
  settings: {
    title: 'Operator Settings',
    noOperator: 'No operator selected.',
    loading: 'Loading settings…',
    error: 'Failed to load settings.',
    save: 'Save changes',
    saving: 'Saving…',
    toastSuccess: 'Settings saved.',
    toastError: 'Failed to save settings.',

    sectionCompany: 'Company',
    sectionCompanyDesc: 'Your public-facing company identity. Slug is read-only.',
    sectionTax: 'Tax & Legal',
    sectionContact: 'Contact & Address',
    sectionLocale: 'Locale',
    sectionIntegrations: 'Integrations',
    sectionIntegrationsDesc: 'Connect third-party services to your operator account.',

    fieldName: 'Company name',
    fieldLegalName: 'Legal name',
    fieldSlug: 'Slug',
    fieldSlugHint: 'Read-only. Used in URLs.',
    fieldTaxId: 'Tax ID',
    fieldTaxIdKind: 'Tax ID type',
    fieldPhone: 'Phone',
    fieldStreet: 'Street',
    fieldCity: 'City',
    fieldPostalCode: 'Postal code',
    fieldRegion: 'Region / State',
    fieldCountry: 'Country (ISO-3166 alpha-2)',
    fieldTimezone: 'Timezone (IANA)',
    fieldLocale: 'Default locale',
    optionNone: '— Select —',

    gmailLoading: 'Loading Gmail status…',
    gmailError: 'Failed to load Gmail status.',
    gmailNotConnected: 'Not connected',
    gmailConnect: 'Connect Gmail',
    gmailConnecting: 'Connecting…',
    gmailConnectError: 'Failed to start Gmail connect.',
    gmailConnectedAt: 'Connected:',
    gmailDisconnect: 'Disconnect',
    gmailDisconnecting: 'Disconnecting…',
    gmailDisconnected: 'Gmail disconnected.',
    gmailDisconnectError: 'Failed to disconnect Gmail.',
  },
  pickupLocations: {
    title: 'Pickup locations',
    subtitle: 'Manage pickup sites and sub-points for bookings.',
    loading: 'Loading locations…',
    error: 'Failed to load locations.',
    empty: 'No locations yet. Add one to get started.',
    addLocation: 'Add location',
    columnName: 'Name',
    columnRoleType: 'Type',
    columnParent: 'Parent site',
    columnEmail: 'Email',
    columnActions: 'Actions',
    actionEdit: 'Edit',
    actionDelete: 'Delete',
    filterPlaceholder: 'Search locations…',
    matches: (n: number, total: number) => `${n} / ${total}`,

    formCreateTitle: 'Add location',
    formEditTitle: 'Edit location',
    formDescription: 'Site-level locations have no parent. Sub-points pick a parent site.',

    fieldName: 'Name',
    fieldRoleType: 'Type',
    fieldParent: 'Parent site (optional)',
    fieldEmail: 'Contact email',
    fieldEmailHotel: 'Hotel contact email',
    fieldParentNone: '— Site level —',
    fieldRoleTypeNone: '— Select type —',

    errorNameRequired: 'Name is required.',
    errorRoleTypeRequired: 'Role type is required.',
    errorEmailFormat: 'Enter a valid email address.',
    errorSubPointDepth: 'Sub-points cannot have their own sub-points.',

    save: 'Save changes',
    saving: 'Saving…',
    create: 'Add location',
    creating: 'Adding…',
    cancel: 'Cancel',

    toastCreated: 'Location added.',
    toastUpdated: 'Location updated.',
    toastDeleted: 'Location deleted.',
    toastError: 'Action failed.',

    deleteDialogTitle: 'Delete location?',
    deleteDialogDescription:
      'This soft-deletes the location. It will disappear from the list immediately. This action can be reversed from the database.',
    deleteDialogConfirm: 'Delete',
    deleteDialogDeleting: 'Deleting…',
    deleteDialogCancel: 'Cancel',
    roleTypesError: 'Failed to load role types.',
  },
  reporting: {
    title: 'Reporting',
    loading: 'Loading bookings…',
    error: 'Failed to load reporting data.',
    empty: 'No bookings in the selected range.',

    kpiBookingsLabel: 'Bookings',
    kpiBookingsHint: 'Total bookings (incl. cancelled)',
    kpiRevenueLabel: 'Revenue',
    kpiRevenueHint: 'Excludes cancelled bookings',
    kpiAvgTicketLabel: 'Average ticket',
    kpiAvgTicketHint: 'Revenue ÷ non-cancelled bookings',

    rangeLabel: 'Date range',
    rangeFromLabel: 'From',
    rangeToLabel: 'To',
    rangeReset: 'Reset',
    rangeAllTime: 'All time',
    rangeLast30: 'Last 30 days',
    rangeLast90: 'Last 90 days',
    rangeThisYear: 'This year',

    chartRevenueTitle: 'Revenue over time',
    chartRevenueDescription:
      'Daily gross revenue, cancelled bookings excluded.',
    chartBookingsTitle: 'Bookings per week',
    chartBookingsDescription:
      'ISO-8601 weeks, bucketed by earliest scheduled date.',

    exportCsv: 'Export CSV',
    exportRowsLabel: (n: number) => `${n} row${n === 1 ? '' : 's'}`,

    cancelledNote: (n: number) =>
      n === 0
        ? ''
        : `${n} cancelled booking${n === 1 ? '' : 's'} excluded from revenue.`,
    mixedCurrencyWarning:
      'Multiple currencies detected — totals shown in the first currency seen.',

    holdedSyncTitle: 'Holded sync',
    holdedSyncBody:
      'Holded sync runs automatically after the Para42 cancellation period. ' +
      'A manual “sync now” trigger from this screen is deferred until the ' +
      'matching FastAPI endpoint ships (landr-m05.9 carry-over).',
  },
  emailTemplates: {
    title: 'Email templates',
    subtitle: 'Customise the transactional emails sent to customers for each booking event.',
    loading: 'Loading email templates…',
    error: 'Failed to load email templates.',
    selectHint: 'Select a template kind and locale on the left to edit.',
    statusCustom: 'Custom',
    statusDefault: 'Default',

    kindLabels: {
      booking_received: 'Booking received',
      hotel_request: 'Hotel request',
      booking_confirmation: 'Booking confirmation',
    } as Record<string, string>,

    localeLabels: {
      de: 'German (de)',
      en: 'English (en)',
    } as Record<string, string>,

    fieldSubject: 'Subject',
    fieldSubjectPlaceholder: 'e.g. Your booking is confirmed',
    fieldBodyHtml: 'HTML body',
    fieldBodyHtmlPlaceholder: '<p>Hello {{customer_name}},</p>',
    fieldBodyText: 'Plain-text body',
    fieldBodyTextPlaceholder: 'Hello {{customer_name}},\n\nYour booking is confirmed.',
    optional: 'optional',

    formAriaLabel: 'Email template editor',

    save: 'Save',
    saving: 'Saving…',
    resetToDefault: 'Reset to default',
    resetting: 'Resetting…',

    toastSaved: 'Template saved.',
    toastSaveError: 'Failed to save template',
    toastReset: 'Template reset to built-in default.',
    toastResetError: 'Failed to reset template',

    previewTitle: 'Preview',
    previewLoading: 'Loading preview…',
    previewError: 'Preview failed',
    previewSelectTemplate: 'Save a template to see the preview.',
    previewStubBanner:
      'Live preview lands when the email sender ships (landr-m05.16). Showing raw template.',
    previewSubject: 'Subject',
    previewHtml: 'HTML',
    previewHtmlTitle: 'Email HTML preview',
    previewText: 'Plain text',
  },
} as const
