// Minimal i18n constants. Decision #70 will layer a real i18n library
// on top later; this keeps user-visible strings centralised so the
// migration is a one-shot find-and-replace.
//
// Terminology stays generic on purpose: LANDR is a universal booking
// platform (paragliding, kayak, ski, yoga…). No vertical-specific
// labels here.

export const t = {
  app: {
    name: 'LANDR Operator Dashboard',
  },
  auth: {
    signInHeading: 'Sign in',
    signInDescription: 'Access your operator dashboard.',
    emailLabel: 'Email',
    emailPlaceholder: 'you@operator.example',
    passwordLabel: 'Password',
    passwordPlaceholder: '••••••••',
    submit: 'Sign in',
    submitting: 'Signing in…',
    signOut: 'Sign out',
    invalidEmail: 'Enter a valid email address.',
    passwordRequired: 'Password is required.',
    genericError: 'Unable to sign in. Check your credentials and try again.',
    loadingSession: 'Loading session…',
  },
  operator: {
    switcherLabel: 'Operator',
    noOperators: 'No operators available for this account.',
    switchTo: 'Switch operator',
    loading: 'Loading operators…',
  },
  nav: {
    sectionMain: 'Workspace',
    dashboard: 'Dashboard',
    bookings: 'Bookings',
    calendar: 'Calendar',
    contacts: 'Contacts',
    products: 'Products',
    reporting: 'Reporting',
    generalApprovals: 'Approvals',
  },
  theme: {
    switchToDark: 'Switch to dark theme',
    switchToLight: 'Switch to light theme',
  },
  userMenu: {
    label: 'User menu',
  },
  bookings: {
    title: 'Bookings',
    empty: 'No bookings yet.',
    loading: 'Loading bookings…',
    error: 'Failed to load bookings.',
    columnDate: 'Date',
    columnCustomer: 'Customer',
    columnProduct: 'Product',
    columnStatus: 'Status',
    columnPrice: 'Price',
    filterPlaceholder: 'Search bookings…',
    detailsTitle: 'Booking',
    detailsClose: 'Close',
  },
  calendar: {
    title: 'Calendar',
    loading: 'Loading calendar…',
    error: 'Failed to load calendar.',
    empty: 'No bookings scheduled.',
    viewMonth: 'Month',
    viewWeek: 'Week',
    viewDay: 'Day',
    rescheduleError: 'Could not reschedule booking.',
  },
  contacts: {
    title: 'Contacts',
    empty: 'No contacts yet.',
    loading: 'Loading contacts…',
    error: 'Failed to load contacts.',
    columnName: 'Name',
    columnEmail: 'Email',
    columnPhone: 'Phone',
    columnCreated: 'Created',
    columnStatus: 'Status',
    columnActivity: 'Activity',
    columnActions: 'Actions',
    filterPlaceholder: 'Search contacts…',
    statusActive: 'Active',
    statusErased: 'Erased',
    actionErase: 'GDPR erase',
    actionAudit: 'Audit log',
    actionEraseShort: 'Erase',
    erasing: 'Erasing…',
    eraseToastSuccess: 'Contact erased and audit log scrubbed.',
    eraseToastError: 'GDPR erase failed.',
    auditTitle: 'Audit log',
    auditEmpty: 'No audit entries.',
    auditLoading: 'Loading audit log…',
    auditError: 'Failed to load audit log.',
    auditClose: 'Close',
    eraseDialogTitle: 'Trigger GDPR erase',
    eraseDialogIntro:
      'This will scrub all PII from this contact, the audit log, and any linked bookings. Commercial fields are preserved per Spanish 6-year retention. This action is irreversible.',
    eraseDialogConfirmLabel: 'Type ERASE to confirm',
    eraseDialogReasonLabel: 'Jurisdiction note (required)',
    eraseDialogReasonPlaceholder: 'e.g. GDPR Art. 17 request via email 2026-05-…',
    eraseDialogCancel: 'Cancel',
    eraseDialogSubmit: 'Erase contact',
    activityRecent: 'Recent: ',
  },
  products: {
    title: 'Products & pricing',
    loading: 'Loading products…',
    error: 'Failed to load products.',
    empty: 'No products yet. Create one to get started.',
    noMatches: 'No products match your filter.',
    filterPlaceholder: 'Search products…',
    listAriaLabel: 'Products',
    createNew: 'New product',
    headingNew: 'New product',
    headingPick: 'Select a product',
    pickHint: 'Pick a product on the left to edit, or create a new one.',
    statusActive: 'Active',
    statusInactive: 'Inactive',

    fieldName: 'Name',
    fieldSlug: 'Slug',
    fieldSlugHint: 'Lowercase, used in URLs. Must be unique per operator.',
    fieldShortDescription: 'Short description',
    fieldDescription: 'Description',
    fieldDurationKind: 'Duration model',
    fieldDurationMinutes: 'Duration (minutes)',
    fieldFixedStartDate: 'Fixed start date',
    fieldFixedEndDate: 'Fixed end date',
    fieldFixedDatesHint: 'Leave both empty for a floating date range.',
    fieldPricingScheme: 'Default pricing scheme',
    fieldProductGroup: 'Product group',
    fieldSortOrder: 'Sort order',
    optionNone: '— None —',

    legendFlags: 'Flags',
    flagActive: 'Active',
    flagPubliclyListed: 'Publicly listed',
    flagNeedsProvider: 'Needs a provider',
    flagNeedsPickup: 'Needs pickup',
    flagRevenueThroughOperator: 'Revenue flows through operator',

    durationSingleDay: 'Single day',
    durationDateRange: 'Date range',
    durationTimeSlot: 'Time slot',

    save: 'Save changes',
    saving: 'Saving…',
    create: 'Create product',
    delete: 'Delete',
    deleting: 'Deleting…',
    confirmDelete:
      'Delete this product? This is a soft delete — it can be restored from the database if needed.',

    formCreateLabel: 'Create product form',
    formEditLabel: 'Edit product form',

    toastCreated: 'Product created.',
    toastUpdated: 'Product updated.',
    toastDeleted: 'Product deleted.',

    errorNameRequired: 'Name is required.',
    errorSlugRequired: 'Slug is required.',
    errorSlugFormat: 'Slug may only contain letters, numbers and hyphens.',
    errorDurationRequired: 'Time-slot products must specify a duration.',
    errorDateRangePaired: 'Set both the start and end date, or neither.',
  },
  generalApprovals: {
    title: 'Pending approvals',
    empty: 'No bookings awaiting general approval.',
    loading: 'Loading approval queue…',
    error: 'Failed to load approval queue.',
    columnDate: 'Date',
    columnCustomer: 'Customer',
    columnProduct: 'Product',
    columnPrice: 'Price',
    columnActions: 'Actions',
    actionApprove: 'Approve',
    actionReject: 'Reject',
    approveDialogTitle: 'Approve booking',
    approveDialogDescription:
      'The booking will move to confirmed. You can add an optional note.',
    rejectDialogTitle: 'Reject booking',
    rejectDialogDescription:
      'The booking will be declined. You can add an optional note for the record.',
    notePlaceholder: 'Optional note…',
    noteLabel: 'Note (optional)',
    cancel: 'Cancel',
    confirmApprove: 'Approve',
    confirmReject: 'Reject',
    approving: 'Approving…',
    rejecting: 'Rejecting…',
    toastApproved: 'Booking approved.',
    toastRejected: 'Booking rejected.',
    toastError: 'Action failed.',
  },
  reporting: {
    title: 'Reporting',
    loading: 'Loading bookings…',
    error: 'Failed to load reporting data.',
    empty: 'No bookings in the selected range.',

    kpiBookingsLabel: 'Bookings',
    kpiBookingsHint: 'Total bookings (incl. cancelled)',
    kpiRevenueLabel: 'Revenue',
    kpiRevenueHint: 'Excludes cancelled bookings',
    kpiAvgTicketLabel: 'Average ticket',
    kpiAvgTicketHint: 'Revenue ÷ non-cancelled bookings',

    rangeLabel: 'Date range',
    rangeFromLabel: 'From',
    rangeToLabel: 'To',
    rangeReset: 'Reset',
    rangeAllTime: 'All time',
    rangeLast30: 'Last 30 days',
    rangeLast90: 'Last 90 days',
    rangeThisYear: 'This year',

    chartRevenueTitle: 'Revenue over time',
    chartRevenueDescription:
      'Daily gross revenue, cancelled bookings excluded.',
    chartBookingsTitle: 'Bookings per week',
    chartBookingsDescription:
      'ISO-8601 weeks, bucketed by earliest scheduled date.',

    exportCsv: 'Export CSV',
    exportRowsLabel: (n: number) => `${n} row${n === 1 ? '' : 's'}`,

    cancelledNote: (n: number) =>
      n === 0
        ? ''
        : `${n} cancelled booking${n === 1 ? '' : 's'} excluded from revenue.`,
    mixedCurrencyWarning:
      'Multiple currencies detected — totals shown in the first currency seen.',

    holdedSyncTitle: 'Holded sync',
    holdedSyncBody:
      'Holded sync runs automatically after the Para42 cancellation period. ' +
      'A manual “sync now” trigger from this screen is deferred until the ' +
      'matching FastAPI endpoint ships (landr-m05.9 carry-over).',
  },
} as const
